# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  database: votereport_development
  username: root
  password:
  socket: /opt/local/var/run/mysqld/mysqld.sock
  
test:
  adapter: mysql
  encoding: utf8
  database: votereport_test
  username: root
  password:
  socket: /opt/local/var/run/mysqld/mysqld.sock
  
production:   
  adapter: mysql
  encoding: utf8
  database: votereport_production
  username: vruser
  password: sa98dadsjafg
  host: 10.0.2.51
