# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  database: votereport_development
  username: root
  password:
  socket: /private/var/mysql/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: votereport_test
  username: root
  password:
  socket: /tmp/mysql.sock
  
production:   
  adapter: mysql
  encoding: utf8
  database: votereport_production
  username: vruser
  password: sa98dadsjafg
  host: 10.0.2.51
