---
googlenewselection:
  name: Google News Election
  url: http://news.google.com/news?ned=in&hl=en&topic=p&output=rss
msnindiaelection:
  name: MSN India Election
  url: http://news.in.msn.com/rss/elections2009.aspx
ibnpolitics:
  name: IBN Politics
  url: http://ibnlive.in.com/xml/rss/ibnpolitics.xml
